import { record, smoothScroll } from './rec.mjs';
import { ensureCursor, clickSel, moveTo } from './cursor.mjs';
const probe = process.argv[2] === 'probe';
await record('order', { width: 1920, height: 1080, script: async (page, { start, mark }) => {
  await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
  await page.waitForTimeout(4500);
  const y = await page.evaluate(() => document.querySelector('#produtos').getBoundingClientRect().top + scrollY - 40);
  await page.evaluate((y) => window.scrollTo(0, y - 500), y);
  await page.waitForTimeout(600);
  await ensureCursor(page, 1500, 900);
  await start();
  await smoothScroll(page, y, 1400);
  await page.waitForTimeout(500);
  mark('card');
  await clickSel(page, '[aria-label^="Ver Cappuccino"]', { ms: 1100, dbl: true, after: 1300 });
  if (probe) await page.screenshot({ path: 'o1.png' });
  mark('panel');
  await clickSel(page, 'label:has-text("Vegetal")', { ms: 900, after: 500 });
  await clickSel(page, '[aria-label="Aumentar quantidade"]', { ms: 800, after: 450 });
  await clickSel(page, '[data-tour="add-cart"]', { ms: 800, after: 1400 });
  if (probe) await page.screenshot({ path: 'o2.png' });
  mark('cart');
  await clickSel(page, 'button:has-text("Seu pedido")', { ms: 900, after: 2200 });
  if (probe) await page.screenshot({ path: 'o3.png' });
  mark('summary');
  await clickSel(page, '.order-summary__checkout', { ms: 900, after: 1200 });
  mark('checkout');
  const typeInto = async (sel, text) => {
    await clickSel(page, sel, { ms: 700, after: 200 });
    await page.keyboard.type(text, { delay: 55 * 4 });
    await page.waitForTimeout(250);
  };
  await typeInto('[data-tour=customer-name] input', 'Marina Costa');
  await typeInto('[data-tour=customer-phone] input', '11987654321');
  await typeInto('[data-tour=customer-address] input', 'Rua Harmonia');
  await typeInto('[data-tour=customer-number] input', '480');
  if (probe) await page.screenshot({ path: 'o4.png' });
  await clickSel(page, '[data-tour=customer-payment]', { ms: 800, after: 700 });
  if (probe) await page.screenshot({ path: 'o4b.png' });
  await clickSel(page, 'text="Pix" >> nth=-1', { ms: 600, after: 300 }).catch((e) => console.log('pix fail', e.message));
  await page.waitForTimeout(500);
  mark('filled');
  await page.evaluate(() => { const b=[...document.querySelectorAll('button')].find(b=>/Enviar pedido/.test(b.textContent)); b && b.scrollIntoView({block:'center', behavior:'smooth'}); });
  await page.waitForTimeout(900);
  await moveTo(page, 'button:has-text("Enviar pedido")', 900);
  await page.waitForTimeout(1600);
  if (probe) await page.screenshot({ path: 'o5.png' });
  mark('end');
}});
